# -*- coding: utf-8 -*-
"""WHO MA Thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7OpIrLK0xaR9GXalXnJ0SMzLidlsw6R
"""

import re
import zipfile
from pathlib import Path
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import spacy
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from scipy import stats

zip_path = Path("WHO_Project-Dataset_Full.zip")
extract_path = Path("./dataset")

if zip_path.exists() and not extract_path.exists():
  print("Extracting dataset locally...")
  with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)
  print("Dataset successfully extracted locally to ./dataset/")

root_path = "./dataset"

print("Loading spaCy language model for advanced text pre-processing...")
nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])


def preprocess_text_spacy(text):
  """Cleans, lemmatizes, and removes stopwords using spaCy to feed into

  the BERTopic embedding pipeline.
  """
  if not text:
    return ""
  doc = nlp(text)
  tokens = [
      token.lemma_
      for token in doc
      if not token.is_stop and not token.is_punct and not token.like_num
  ]
  return " ".join(tokens)


technical_keywords = [
    "evidence-based",
    "science-led",
    "data-driven",
    "rigorous",
    "technical",
    "objective",
]
moral_keywords = [
    "solidarity",
    "global solidarity",
    "health equity",
    "universal access",
    "multilateral",
    "collective responsibility",
]
uncertainty_diagnostics = ["interim", "preliminary", "evolving", "unknown", "emerging"]

all_thematic_keywords = (
    technical_keywords + moral_keywords + uncertainty_diagnostics
)


def clean_and_extract(file_path):
  """Extracts raw text from PDF documents and normalises whitespace/case while

  strictly preserving hyphens and multi-word phrases for regex evaluation.
  """
  try:
    import fitz

    with fitz.open(file_path) as doc:
      text = " ".join([page.get_text("text") for page in doc])
      clean_text = text.replace(file_path.stem.replace("_", " "), "")
      clean_text = clean_text.lower()
      clean_text = re.sub(r"\s+", " ", clean_text).strip()
      return clean_text
  except Exception as e:
    print(f"Error in text extraction for {file_path.name}: {e}")
    return None


def get_word_count(text):
  return len(text.split()) if text else 0


def analyze_text(text, word_count):
  """Computes word-boundary-safe regex matches for each track, normalised per 10,000 words."""
  if not text or word_count == 0:
    return pd.Series([0.0, 0.0, 0.0])

  multiplier = 10000 / word_count

  def count_pattern(kw_list):
    total_matches = 0
    for kw in kw_list:
      pattern = r"\b" + re.escape(kw) + r"\b"
      total_matches += len(re.findall(pattern, text))
    return total_matches * multiplier

  tech_score = count_pattern(technical_keywords)
  moral_score = count_pattern(moral_keywords)
  uncert_score = count_pattern(uncertainty_diagnostics)

  return pd.Series([tech_score, moral_score, uncert_score])


def extract_kwic_contexts(text, keyword, window=7):
  """Finds every word-boundary-safe occurrence of `keyword` in the full text

  and returns context windows of `window` words on each side.
  """
  if not text:
    return []
  contexts = []
  pattern = r"\b" + re.escape(keyword) + r"\b"
  for match in re.finditer(pattern, text):
    start_char, end_char = match.span()
    before_words = text[:start_char].split()[-window:]
    after_words = text[end_char:].split()[:window]
    context = (
        f"{' '.join(before_words)} [{keyword.upper()}] {' '.join(after_words)}"
    )
    contexts.append(context)
  return contexts


def build_master_corpus(base_folder):
  """Crawls nested subdirectories systematically, extracting text from PDFs

  and preparing both raw text (for KWIC/dictionary analysis) and preprocessed
  text (for BERTopic).
  """
  base_path = Path(base_folder)
  pdf_files = list(base_path.glob("**/*.pdf"))

  print(
      f"Discovered {len(pdf_files)} PDF items across folder architecture."
      " Commencing extraction..."
  )

  target_categories = [
      "_SituationReports",
      "_InterimGuidelines",
      "_Statements",
      "_StrategicPlans",
      "_DirectorGeneral",
      "_AFRO",
      "_EMRO",
      "_EURO",
      "_PAHO",
      "_SEARO",
      "_WPRO",
  ]

  all_records = []
  skipped_no_category = 0

  for f in pdf_files:
    assigned_category = None
    for parent in f.parents:
      if parent.name in target_categories:
        assigned_category = parent.name.replace("_", "")
        break

    if not assigned_category:
      skipped_no_category += 1
      continue

    if assigned_category in ["AFRO", "EMRO", "EURO", "PAHO", "SEARO", "WPRO"]:
      assigned_category = f"Speeches_{assigned_category}"
    elif assigned_category == "DirectorGeneral":
      assigned_category = "DG_Speeches"

    date_match = re.search(r"(\d{4}-\d{2}-\d{2})", f.stem)
    if date_match:
      doc_date = pd.to_datetime(date_match.group(1))
      doc_year = doc_date.year

      if 2020 <= doc_year <= 2023:
        content = clean_and_extract(f)
        if content and len(content.split()) > 10:
          processed_text = preprocess_text_spacy(content)
          all_records.append({
              "date": doc_date,
              "year": doc_year,
              "category": assigned_category,
              "filename": f.stem,
              "text": content,
              "processed_text": processed_text,
              "word_count": get_word_count(content),
          })

  master_df = pd.DataFrame(all_records)
  print(
      f"Ingestion engine complete. Successfully processed {len(master_df)}"
      " documents."
  )
  if skipped_no_category:
    print(
        f"Note: {skipped_no_category} PDF(s) had no matching category folder in"
        " their path and were skipped."
    )
  return master_df


master_data = build_master_corpus(root_path)

if not master_data.empty:
  print("\nQuantifying dictionary-based thematic frequency metrics...")
  freq_results = master_data.apply(
      lambda row: analyze_text(row["text"], row["word_count"]), axis=1
  )
  freq_results.columns = [
      "Technical_Track",
      "Moral_Track",
      "Uncertainty_Diagnostic",
  ]
  master_data = pd.concat([master_data, freq_results], axis=1)

  def assign_phase(year):
    if year == 2020:
      return "Phase 1 (2020)"
    elif year == 2021:
      return "Phase 2 (2021)"
    else:
      return "Phase 3 (2022-2023)"

  master_data["phase"] = master_data["year"].apply(assign_phase)

  technical_categories = {
      "SituationReports",
      "InterimGuidelines",
      "StrategicPlans",
  }
  master_data["audience_type"] = master_data["category"].apply(
      lambda cat: "Technical" if cat in technical_categories else "Political"
  )

  master_data["speech_region"] = master_data["category"].apply(
      lambda cat: (
          "Geneva_HQ"
          if cat == "DG_Speeches"
          else (
              cat.replace("Speeches_", "")
              if cat.startswith("Speeches_")
              else None
          )
      )
  )

  tracked_years = sorted(master_data["year"].unique())
  for current_year in tracked_years:
    print("\n" + "=" * 60)
    print(f"EXECUTING CHRONOLOGICAL PIPELINE RUN: {current_year}")
    print("=" * 60)

    year_df = (
        master_data[master_data["year"] == current_year]
        .sort_values("date")
        .reset_index(drop=True)
    )
    unique_categories = sorted(year_df["category"].unique())

    summary_stats = year_df.groupby("category")[[
        "Technical_Track",
        "Moral_Track",
        "Uncertainty_Diagnostic",
    ]].mean()
    table_filename = f"Statistical_Summary_Table_{current_year}.csv"
    summary_stats.to_csv(table_filename)
    print(f"Cross-section data spreadsheet exported to: {table_filename}")
    print(summary_stats.round(2))

    for cat in unique_categories:
      cat_subset = year_df[year_df["category"] == cat]
      if cat_subset.empty:
        continue

      fig, ax = plt.subplots(figsize=(12, 6))
      ax.plot(
          cat_subset["date"],
          cat_subset["Technical_Track"],
          color="#2980B9",
          label="Technical Track",
          linewidth=2.5,
      )
      ax.plot(
          cat_subset["date"],
          cat_subset["Moral_Track"],
          color="#27AE60",
          label="Moral Track",
          linewidth=2.5,
      )

      display_title = (
          f"Institutional Register Profile: {cat.replace('Speeches_', 'Region: ')}"
          if "Speeches_" in cat
          else f"Institutional Register Profile: {cat}"
      )
      if cat == "DG_Speeches":
        display_title = "Geneva HQ: Director-General Speeches"

      ax.set_title(
          f"{display_title} ({current_year})",
          fontsize=14,
          fontweight="bold",
          pad=15,
      )
      ax.set_ylabel("Normalized Freq / 10k Words", fontsize=11)
      ax.grid(True, linestyle=":", alpha=0.5)

      ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))
      ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
      fig.autofmt_xdate()

      ax.set_xlabel("Timeline Evolution", fontsize=11, labelpad=10)
      ax.legend(
          loc="upper right", fontsize=10, frameon=True, facecolor="#FAFAFA"
      )

      chart_output_name = f"{current_year}_Profile_{cat}.jpg"
      plt.savefig(chart_output_name, dpi=300, bbox_inches="tight")
      plt.close()

    kwic_records = []
    for _, row in year_df.iterrows():
      for kw in all_thematic_keywords:
        for context in extract_kwic_contexts(row["text"], kw, window=7):
          kwic_records.append({
              "Year": current_year,
              "Category_Track": row["category"],
              "Date": row["date"].strftime("%Y-%m-%d"),
              "File_Source": row["filename"],
              "Matched_Keyword": kw,
              "Context_Window": context,
          })

    if kwic_records:
      kwic_df = pd.DataFrame(kwic_records)
      kwic_output_path = f"KWIC_Comprehensive_Matrix_{current_year}.csv"
      kwic_df.to_csv(kwic_output_path, index=False)
      print(f"Structural context matrix sheet saved to: {kwic_output_path}")

  print("\n" + "=" * 60)
  print("DICTIONARY EXPECTATION-LEVEL COMPARISON TABLES (E1, E2, E3) & T-TESTS")
  print("=" * 60)

  e1_table = master_data.groupby("phase")[[
      "Technical_Track",
      "Moral_Track",
      "Uncertainty_Diagnostic",
  ]].mean()
  e1_table = e1_table.reindex(
      ["Phase 1 (2020)", "Phase 2 (2021)", "Phase 3 (2022-2023)"]
  )
  e1_table.to_csv("E1_Temporal_Comparison.csv")
  print(e1_table.round(2))

  p1_moral = master_data[master_data["phase"] == "Phase 1 (2020)"]["Moral_Track"]
  p3_moral = master_data[master_data["phase"] == "Phase 3 (2022-2023)"]["Moral_Track"]
  t_e1, p_e1 = stats.ttest_ind(p1_moral, p3_moral, equal_var=False)
  print(f"[E1 T-Test] Phase 1 vs Phase 3 Moral Track: t = {t_e1:.2f}, p = {p_e1:.4f}")

  speech_only = master_data[master_data["speech_region"].notna()]
  e2_table = speech_only.groupby("speech_region")[[
      "Technical_Track",
      "Moral_Track",
  ]].mean()
  e2_table.to_csv("E2_Spatial_Comparison_SpeechesOnly.csv")
  print(e2_table.round(2))

  geneva_moral = speech_only[speech_only["speech_region"] == "Geneva_HQ"]["Moral_Track"]
  regional_moral = speech_only[speech_only["speech_region"] != "Geneva_HQ"]["Moral_Track"]
  t_e2, p_e2 = stats.ttest_ind(geneva_moral, regional_moral, equal_var=False)
  print(f"[E2 T-Test] Geneva HQ vs Pooled Regional Offices (Moral Track): t = {t_e2:.2f}, p = {p_e2:.4f}")

  e3_table = master_data.groupby("audience_type")[[
      "Technical_Track",
      "Moral_Track",
  ]].mean()
  e3_table.to_csv("E3_Audience_Comparison.csv")
  print(e3_table.round(2))

  tech_audit = master_data[master_data["audience_type"] == "Technical"]["Technical_Track"]
  pol_audit = master_data[master_data["audience_type"] == "Political"]["Technical_Track"]
  t_e3, p_e3 = stats.ttest_ind(tech_audit, pol_audit, equal_var=False)
  print(f"[E3 T-Test] Technical vs Political Audience (Technical Track): t = {t_e3:.2f}, p = {p_e3:.4f}")

  print("\n" + "=" * 60)
  print("INITIALIZING BERTOPIC MODELING PIPELINE")
  print("=" * 60)

  embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
  docs = master_data["processed_text"].tolist()
  topic_model = BERTopic(embedding_model=embedding_model, verbose=True)
  topics, probabilities = topic_model.fit_transform(docs)

  master_data["topic"] = topics
  master_data["topic_probability"] = probabilities

  print("\nTop Discovered Topics across Corpus:")
  print(topic_model.get_topic_info().head(10))
  topic_model.get_topic_info().to_csv("BERTopic_Summary_Info.csv", index=False)

  speech_only = master_data[master_data["speech_region"].notna()]

  phase_topic_dist = pd.crosstab(
      master_data["phase"], master_data["topic"], normalize="index"
  )
  phase_topic_dist.to_csv("E1_BERTopic_Phase_Distribution.csv")

  region_topic_dist = pd.crosstab(
      speech_only["speech_region"], speech_only["topic"], normalize="index"
  )
  region_topic_dist.to_csv("E2_BERTopic_Spatial_Distribution.csv")

  audience_topic_dist = pd.crosstab(
      master_data["audience_type"], master_data["topic"], normalize="index"
  )
  audience_topic_dist.to_csv("E3_BERTopic_Audience_Distribution.csv")

  print(
      "\nIntegrated master execution cycle completed successfully with both"
      " dictionary metrics, independent samples t-tests, and BERTopic outputs."
  )
else:
  print("Process Aborted: Input path check yielded empty document frame pools.")